### ISSUE TITLE
在不呼唤bot的情况下触发回答

### ISSUE THREAD

**Issue by NathanSummer** [KarisAya/nonebot_plugin_kawaii_robot#13]
有没有方法能在不@也不发出机器人名字的时候通过关键词触发回答

**Comment by NathanSummer** [comment]
> 有没有方法能在不@也不发出机器人名字的时候通过关键词触发回答

比如新建一个词库，使其中的触发词在不呼唤bot的情况下生效

**Comment by KiDisplayBlueScreen** [comment]
把 talk = on_message(rule = to_me(), permission = permission, priority=99, block=False) 里面的rule = to_me()删除就行了

**Comment by lgc2333** [comment]
新版4.0.0有了不at时候的概率回复，如果还不能满足你的需求的话，可以看看 https://github.com/lgc-NB2Dev/nonebot-plugin-autoreply
