### ISSUE TITLE
有没有办法关闭某个类型的回复

### ISSUE THREAD

**Issue by olisc3567** [KarisAya/nonebot_plugin_kawaii_robot#2]
如题，我使用另一个mirai的聊天插件有重复的功能（at机器人回复等）会导致机器人一次回两句，而这个插件的部分词库又比mirai插件的更合适，所以我想关闭此插件的部分功能让两者不会冲突。

**Comment by KarisAya** [comment]
at回复的解决方法：
这个at回复的优先级已经是99了，优先级靠上面的插件没做阻断就会继续向下触发。可以进插件的_init_.py把at触发的函数先删掉。后续我可能会更新可以控制at回复的开关
（挖坑+1）
关键词回复的解决方法：
关键词太多了，是触发后比对字典key检索的，以后还会更新，没法单独关闭 。不过你可以通过修改插件文件夹下json文件的方式关闭某个回复。
找到leaf.json还有data.json修改你想要关闭的关键词。这个词库是直接文字编码的所以用记事本就可以改。
可以把你想关掉的字典整个删掉，
不过我建议在字典key上添加一下绝对用不到的前缀。
比如之前的触发关键词是"你好"然后你改成"（已删除）你好"这样就把触发关键词变成【（已删除）你好 】
你再发【你好】就不会触发这个词库回复
