### ISSUE TITLE
设置成-1就报错

### ISSUE THREAD

**Issue by qsm-mz-hn** [KarisAya/nonebot_plugin_kawaii_robot#23]
![PixPin_2024-03-15_19-29-56](https://github.com/KarisAya/nonebot_plugin_kawaii_robot/assets/108866283/130a7eca-fd49-4137-8216-dd0ecf40b139)
![PixPin_2024-03-15_19-31-06](https://github.com/KarisAya/nonebot_plugin_kawaii_robot/assets/108866283/eca0d445-c6b6-43ac-905d-611e72839dd5)

**Comment by lgc2333** [comment]
https://github.com/KarisAya/nonebot_plugin_kawaii_robot/releases/tag/v4.1.0.post1
