### ISSUE TITLE
如何切换词库

### ISSUE THREAD

**Issue by L-time** [KarisAya/nonebot_plugin_kawaii_robot#3]
如题，两个词库如何切换，是删掉其中一个就好吗？

**Comment by KarisAya** [comment]
两个词库都在使用，leaf.json的key几乎不与data.json重合,是那个词库的补充，所以不用切换。

**Comment by L-time** [comment]
> 两个词库都在使用，leaf.json的key几乎不与data.json重合,是那个词库的补充，所以不用切换。 删掉其中某个词库可能会出现一些问题，需要测试一下。

那能扩展词库吗？比如我又写了一个autoreply.json，我是否需要更改源码让这个词库加进来？

**Comment by KarisAya** [comment]
目前只可以修改自带的两个json中来添加个人词库。不过我计划下次更新可以随意添加个人词库的功能。
预计今晚或明天。

**Comment by KarisAya** [comment]
> > 两个词库都在使用，leaf.json的key几乎不与data.json重合,是那个词库的补充，所以不用切换。 删掉其中某个词库可能会出现一些问题，需要测试一下。
> 
> 那能扩展词库吗？比如我又写了一个autoreply.json，我是否需要更改源码让这个词库加进来？

插件已经更新到2.0版本，可以试一试。

**Comment by Longxuanyue** [comment]
我自己写了一个词库，但是运行后完全无法触发

**Comment by Longxuanyue** [comment]
> 我自己写了一个词库，但是运行后完全无法触发

而且在插件自带的两个词库中进行修改也没有任何效果，这是怎么回事？
