### ISSUE TITLE
请问该如何关闭私聊回复

### ISSUE THREAD

**Issue by LiebeVerletzt** [KarisAya/nonebot_plugin_kawaii_robot#4]
如题，因为一些原因暂时使用bot号作为主号使用，不希望私聊会被干扰
不过自己完全没接触过python所以手动改代码苦手

**Comment by KarisAya** [comment]
插件中__init__.py

26行

@ai.handle()
async def _(event: MessageEvent):

改成

@ai.handle()
async def _(event: GroupMessageEvent):

咱就不更新插件了，手动改吧qwq

**Comment by KarisAya** [comment]
稍后升级到通过配置文件关闭私聊回复的版本

**Comment by KarisAya** [comment]
现在插件升级了权限控制功能，
可以通过添加配置
LEAF_PERMISSION = "GROUP"
修改成仅群聊回复
记得带引号“”

**Comment by LiebeVerletzt** [comment]
感谢特地且即时的更新！
不过自己太激动忘了备份所以要重新魔改配置文件了T_T
希望能早一点能自己写这些功能
