### ISSUE TITLE
可不可以单独配置私聊的回复模式

### ISSUE THREAD

**Issue by WindraiteLesd** [KarisAya/nonebot_plugin_kawaii_robot#5]
像LEAF_REPLY_TYPE那样，因为我的bot是nonebot2+yunzai，因为两个bot之间不会互相阻断，所以其他人在私聊发送指令使用yunzai的功能时会触发bot回复不明白的词库，我希望可以单独关闭私聊中不明白的回复词库
![image](https://user-images.githubusercontent.com/104503043/186070942-34588a20-f8cf-4e49-a311-ce6dba06825d.png)

**Comment by KarisAya** [comment]
关于这个情况我会增加一个配置项来配置本插件的忽略词。
如果是以忽略词开头就不会触发此插件的回复。
无须为私聊单独配置。
预计明天更新。

**Comment by WindraiteLesd** [comment]
yunzai的指令有些多，忽略词手动添加的量有些大

**Comment by KarisAya** [comment]
> yunzai的指令有些多，忽略词手动添加的量有些大

如果yunzai的指令全部是以"#"开头的那么只需要在忽略词里配置一个”#“就好了

**Comment by WindraiteLesd** [comment]
这个其实看情况的，因为yunzai不强制使用#，再加上很多插件一部分指令需要#，一部分又不需要，还有的是可有可无...

**Comment by WindraiteLesd** [comment]
> > yunzai的指令有些多，忽略词手动添加的量有些大
> 
> 如果yunzai的指令全部是以"#"开头的那么只需要在忽略词里配置一个”#“就好了

这个其实看情况的，因为yunzai不强制使用#，再加上很多插件一部分指令需要#，一部分又不需要，还有的是可有可无...

**Comment by KarisAya** [comment]
已更新 3.2.0

**Comment by KarisAya** [comment]
> > > yunzai的指令有些多，忽略词手动添加的量有些大
> > 
> > 
> > 如果yunzai的指令全部是以"#"开头的那么只需要在忽略词里配置一个”#“就好了
> 
> 这个其实看情况的，因为yunzai不强制使用#，再加上很多插件一部分指令需要#，一部分又不需要，还有的是可有可无...

因为把群聊和私聊分出来判断量会多出一倍，那样代码过于臃肿，
添加忽略词可以精细化的自定义，只是配置有些麻烦。
