### ISSUE TITLE
多个屏蔽词报错

### ISSUE THREAD

**Issue by NachoNeko-daisuki** [KarisAya/nonebot_plugin_kawaii_robot#7]
![20221210224108](https://user-images.githubusercontent.com/41470933/207536102-2f9fa858-0dfc-45af-9af4-bebea9d8f0c6.jpg)

**Comment by Goodzzzz** [comment]
屏蔽词作者标注的是字符串，经过我的测试，只能是数字，加双引号就报错。

**Comment by NachoNeko-daisuki** [comment]
> 屏蔽词作者标注的是字符串，经过我的测试，只能是数字，加双引号就报错。

这个报错似乎是忽略词的config不规范引起的？我已经提pr了，修改后我没有再出现报错，同样的报错可以按我pr修改 #8
