### ISSUE TITLE
自己写的词库在bot上显示加载成功但是无效

### ISSUE THREAD

**Issue by YouYouLip** [KarisAya/nonebot_plugin_kawaii_robot#9]
![QQ图片20221221144905](https://user-images.githubusercontent.com/119958263/208839685-c8e4f865-2445-448e-ac2b-30ed55dc0e67.png)
如图 显示加载成功 但是触发不了 是utf-8无bom的形式 请问怎么解决

**Comment by YouYouLip** [comment]
等等我好像发现了 可能是我的问题 我测试了一下 我在关键词上面写上了bot的名字 含有bot名字的均无法触发 类似于 关键词抱抱可以触发 但是加上机器人的名字带上抱抱就会识别错误

**Comment by YouYouLip** [comment]
破案了 词库中不能加机器人的昵称 这个对于群聊来说比较致命 容易牛头不对马嘴

**Comment by KarisAya** [comment]
> 破案了 词库中不能加机器人的昵称 这个对于群聊来说比较致命 容易牛头不对马嘴

能详细描述一下吗

**Comment by YouYouLip** [comment]
> > 破案了 词库中不能加机器人的昵称 这个对于群聊来说比较致命 容易牛头不对马嘴
> 
> 能详细描述一下吗

好比如词库其中的内容是早上好 这个是可以正常识别并运行的 但是如果是加上机器人的名字并且早上好 好比如机器人叫小美 词库中写上小美早上好 依然能显示加载只不过均无法触发 好久之前的事了 不知道是带上机器人名字的词库触发不了还是全都触发不了

**Comment by KarisAya** [comment]
> > > 破案了 词库中不能加机器人的昵称 这个对于群聊来说比较致命 容易牛头不对马嘴
> > 
> > 
> > 能详细描述一下吗
> 
> 好比如词库其中的内容是早上好 这个是可以正常识别并运行的 但是如果是加上机器人的名字并且早上好 好比如机器人叫小美 词库中写上小美早上好 依然能显示加载只不过均无法触发 好久之前的事了 不知道是带上机器人名字的词库触发不了还是全都触发不了

以bot名字开头的指令会被响应器处理成tome并且CommandArg收到的指令是去掉bot名字的，比如”小美早上好“会被处理成“早上好”，这样的话字典就对不上了，所以这条字典就失效了。

**Comment by YouYouLip** [comment]
> > > > 破案了 词库中不能加机器人的昵称 这个对于群聊来说比较致命 容易牛头不对马嘴
> > > 
> > > 
> > > 能详细描述一下吗
> > 
> > 
> > 好比如词库其中的内容是早上好 这个是可以正常识别并运行的 但是如果是加上机器人的名字并且早上好 好比如机器人叫小美 词库中写上小美早上好 依然能显示加载只不过均无法触发 好久之前的事了 不知道是带上机器人名字的词库触发不了还是全都触发不了
> 
> 以bot名字开头的指令会被响应器处理成tome并且CommandArg收到的指令是去掉bot名字的，比如“小美早上好”会被处理成“早上好”，这样的话字典就对不上了，所以这条字典就失效了。

了解了 这下彻底破案了
